services:
    avathar.bbguildlineage2.installer:
        class: avathar\bbguildlineage2\game\lineage2_installer
        arguments:
            - '@dbal.conn'
            - '@cache.driver'
            - '@config'
            - '@user'

    avathar.bbguildlineage2.provider:
        class: avathar\bbguildlineage2\game\lineage2_provider
        arguments:
            - '@avathar.bbguildlineage2.installer'
            - '@ext.manager'
        tags:
            - { name: bbguild.game_provider }
